[FEAT] mongo repl and standalone configs in colibri server with symbo…
OpenG/ansible-mongodb pull request #3
Opened 2019-08-30 10:53 UTC by martynas-openg

Not yet tested on production;
Will propably remove backuping the mongod.conf file task after testing on production because it becomes a symlink;

2019-08-30 11:01 UTC, Ben10k requested changes

2019-08-30 11:01 UTC, Ben10k commented on templates/mongod.standalone.conf.j2
> +  bindIp: {% if mongodb_internal_vpn_ip is defined %}{{ mongodb_internal_vpn_ip }},{% endif %}127.0.0.1
The reason for doing this was to remove the necessary bind to the VPN IP that is not present after the reboot.
Remove the if statement `{% if mongodb_internal_vpn_ip is defined %}{{ mongodb_internal_vpn_ip }},{% endif %}` and bind only to the localhost (127.0.0.1)

2019-08-30 11:01 UTC, Ben10k commented on tasks/main.yml
> +    src: start_mongo_with_backup.sh
The script executes a restart and the name shows that it only starts the mongod service

2019-08-30 11:01 UTC, Ben10k commented on tasks/main.yml
> +- name: remove previous config incase of it being not a symlink
in case

2019-08-30 11:15 UTC, Ben10k requested changes

2019-08-30 11:15 UTC, Ben10k commented on templates/mongod.repl.conf.j2
> +  bindIp: 127.0.0.1
The if statement must be present in the repl config

2019-08-30 12:35 UTC, Ben10k approved these changes

2019-09-02 15:38 UTC, d0nce approved these changes

2019-09-02 15:38 UTC, merged